---
title: "Dépouillement de l'enquête Jeunes diplômés Ipag 2015"
author: "Bruno Fischer"
date: "27 juin 2016"
output:
  word_document:
    fig_caption: yes
    fig_width: 7
    toc: yes
  html_document:
    css: customex2.css
    number_sections: yes
    theme: readable
subtitle: 'Dépouillement question par question, partie 2 : ALTERNANCE +'
---


```{r init, include=FALSE}
library(knitr)
opts_chunk$set(echo = FALSE, warning = FALSE)
# opts_chunk$set(echo = FALSE, fig.width = 5, fig.height = 5)
options(digits = 2, scipen = 7)
# width + heights figures constants
dkfigwidth <- 5
dkfigheight <- 5
lkfigwidth <- 8
lkfigheight <- 7
```


```{r, warning=FALSE, include=FALSE}
#' Loading packages and code
#' ================

library(dplyr)
library(ggplot2)
library(reshape2)

#' Sourcing more code
#' ================
#'
# more code
# workdir <- getwd()
maindir <- ".."
mcodir <- "addcode"
code1name <- "utils.R"
source(file.path(maindir, mcodir, code1name))

# more code :  standard functions
stdfundir <- "standardfunctions"
stdfunname <- "standardfunctionsV5.R"
source(file.path(maindir, stdfundir, stdfunname))


# more code: results storing and retrieving 
# ~~==> attention: efface (réinitialise) la liste des résultats de traitement~~

rdirect <- "rcode"
codresultats <- "funcoderesultats.R"
codepath <- file.path(maindir, rdirect, codresultats)
source(file.path(maindir, rdirect, codresultats))

```


```{r getdata}
#'
#' Récupération des données prétraitées
#' ====================================
#'

# path(rda)
datadir2 <- "data2"
alldatapath <- file.path(maindir, datadir2, "alldata.Rda")
# loading
whatload <- load(alldatapath)
# verification
# whatload
```


```{r getallresults}
#'
#' lecture des résultats de traitement
#' ====================================
#'

# path(rda)
datadir3 <- "data3"
allresultspath <- file.path(maindir, datadir3, "allresults.Rda")
# message(getwd())
# message(allresultspath)
# loading
whatload <- load(allresultspath)
# verification
# whatload
```



dépouillement
========================


### 25 Depuis combien de temps êtes-vous à la recherche d'un emploi ? {-}


```{r, fig.height=lkfigheight}
res <- getresult("situation_temps_recherce")

numc <- res$numcases
ptable <- res$ptable
colnames(ptable) <- c("Réponse", "Effectif", "%")
pval <- res$chi2$test1$p.value
seuilsignif <- 0.05
seuilpeusignif <- 0.1
estsignif <- ifelse(pval < seuilsignif,"est", ifelse(pval < seuilpeusignif,"est peu", "n'est pas"))


plot <- res$plot1
```

Il y a `r numc` répondants à cette question


```{r}

kable(ptable, caption = "Table des réponses", align = 'c', digits = 2)
```

<!-- La différence des effectifs des catégories `r estsignif` significative (Chi² : p-valeur = `r pval*100`%) --> 

```{r}
plot2 <- plot + labs(x = "", y = "Poucent")
plot2 + theme(axis.text.x = element_text(angle=45, hjust=1))
```

